### ISSUE TITLE
[BUG WARN] - Video duration is incorrect when fetched with popyt

### ISSUE THREAD

**Issue by jasonhaxstuff** [StarArmyDev/starmusic#7]
### Descripción del problema

Hello, creator of popyt here. There is an error with how the duration is set with popyt on videos here: https://github.com/StarArmyDev/starmusic/blob/main/src/Music.ts#L604
The issue is that popyt separates the length of the video into two properties, `video.minutes` and `video.seconds`. The `minutes` property is how many minutes are in the video, and the `seconds` property is how many seconds are after that. For example, this would be formatted as `${video.minutes}:${video.seconds}`. The program treats it as if the `video.seconds` property contains the total number of seconds in the video.

Thanks for using popyt!

**Comment by DavichoStar** [comment]
Hello @jasonhaxstuff, thanks for noticing. I had already noticed and corrected it in time on the line: https://github.com/StarArmyDev/starmusic/blob/main/src/index.ts#L96 but I forgot that I also occupied it on that line that you mentioned.

Nice to use popyt, good job.
